# Generated by Django 5.2.2 on 2025-08-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
